import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` bg-white text-black min-h-screen py-8 mx-auto lg:px-40 md:px-20 px-5  ${inter.className}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
